/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorDatos;
import java.io.File;
import java.io.IOException;
import java.time.*;
import java.util.ArrayList;
import java.util.Random;
import java.time.Year;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Servicio;
import modelo.Taxi;
import modelo.Usuario;

/**
 *
 * @author s204e14
 */
public class ProgramaTaxis extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaTaxis
     */
    public ProgramaTaxis() {

        initComponents();
        manDatos = new ManejadorDatos();

        try {
            usuarios = new File("D:\\TaxisPrimerEntrega\\Usuarios.txt");
            listUsuarios = manDatos.cargarUsuarios(usuarios);
            JOptionPane.showMessageDialog(this, "Datos cargados correctamente", "Carga de datos", JOptionPane.INFORMATION_MESSAGE);
            listmodelUsuarios.removeAllElements();
            for (Usuario u : listUsuarios) {
                listmodelUsuarios.addElement(u);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Datos Corruptos", "Error Carga Usuarios", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Carga Usuarios", JOptionPane.ERROR_MESSAGE);
        }

        try {
            servicios = new File("D:\\TaxisPrimerEntrega\\Servicios.txt");
            listServicios = manDatos.cargarServicios(servicios);
            listmodelServicios.removeAllElements();
            for (Servicio s : listServicios) {
                listmodelServicios.addElement(s);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Datos Corruptos", "Error Carga Servicios", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Carga Servicios", JOptionPane.ERROR_MESSAGE);
        }
        try {
            taxis = new File("D:\\TaxisPrimerEntrega\\Taxis.txt");
            listTaxis = manDatos.cargarTaxis(taxis);

            listmodelTaxis.removeAllElements();
            for (Taxi t : listTaxis) {
                listmodelTaxis.addElement(t);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Datos Corruptos", "Error Carga Taxis", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Carga Taxis", JOptionPane.ERROR_MESSAGE);
        }
        this.setLocationRelativeTo(null);
        this.setTitle("NUEVO SERVICIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaNuevoUsuario = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDUsuario = new javax.swing.JTextField();
        txtDireccionPorDefecto = new javax.swing.JTextField();
        txtTelefonoFijo = new javax.swing.JTextField();
        txtCelularVentanaUsuario = new javax.swing.JTextField();
        btnCrearUsuario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnGenerarID = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        VentanaTaxis = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listmodelTaxis = new DefaultListModel();
        jListTaxis = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblIdConductor = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblPoliza = new javax.swing.JLabel();
        lblSeguro = new javax.swing.JLabel();
        lblFechaTecno = new javax.swing.JLabel();
        btnEscoger = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnTaxiConMasServicios = new javax.swing.JButton();
        btnMostrarTodosTaxis = new javax.swing.JButton();
        VentanaMostarUsuarios = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblIDUsuario = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelFijo = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lbltelfijo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        btnSeleccionarUsuario = new javax.swing.JButton();
        btnUsuariosFrecuentes = new javax.swing.JButton();
        btnViualizarViajes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listmodelUsuarios = new DefaultListModel();
        jListUsuarios = new javax.swing.JList<>();
        VentanaMostrarServicios = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listmodelServicios = new DefaultListModel();
        jListServicios = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblIDServicioVentanaMostrarServicio = new javax.swing.JLabel();
        lblIDUsuarioVentanaMostrarServicio = new javax.swing.JLabel();
        lblDireccionOrigenVentanaMostrarServicio = new javax.swing.JLabel();
        lblFechaServicioVentanaMostrarServicio = new javax.swing.JLabel();
        lblHoraServicioVentanaMostrarServicio = new javax.swing.JLabel();
        lblPlacaTaxiVentanaMostrarServicio = new javax.swing.JLabel();
        lblValorServicioVentanaMostrarServicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCelularVentanaServicio = new javax.swing.JTextField();
        txtDireccionOrigen = new javax.swing.JTextField();
        txtPlacataxi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarUsuario = new javax.swing.JButton();
        btnBuscarTaxi = new javax.swing.JButton();
        btnCrearServicio = new javax.swing.JButton();
        btnMostrarUsuarios = new javax.swing.JButton();
        btnMostrarServicios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtValorServicio = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnAgregarUsuarios = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        VentanaNuevoUsuario.setTitle("Nuevo Usuario");
        VentanaNuevoUsuario.setMinimumSize(new java.awt.Dimension(700, 630));
        VentanaNuevoUsuario.setModal(true);
        VentanaNuevoUsuario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                VentanaNuevoUsuarioWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Nombre");

        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("ID Usuario");

        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("Direccion Por Defecto");

        jLabel8.setForeground(new java.awt.Color(51, 0, 255));
        jLabel8.setText("Telefono Fijo");

        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("Celular");

        txtIDUsuario.setEditable(false);
        txtIDUsuario.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(0, 0, 153));
        btnCrearUsuario.setText("Crear Usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 255));
        jLabel10.setText("NUEVO USUARIO");

        btnGenerarID.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarID.setForeground(new java.awt.Color(51, 0, 255));
        btnGenerarID.setText("Generar ID");
        btnGenerarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarIDActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/useridpng.png"))); // NOI18N
        jButton4.setEnabled(false);

        jLabel30.setForeground(new java.awt.Color(51, 0, 255));
        jLabel30.setText("Correo Electrónico");

        jLabel31.setForeground(new java.awt.Color(51, 0, 255));
        jLabel31.setText("Contraseña");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(txtTelefonoFijo)
                    .addComponent(txtCelularVentanaUsuario)
                    .addComponent(txtCorreoElectronico)
                    .addComponent(txtContraseña)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtIDUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarID))
                    .addComponent(txtDireccionPorDefecto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel10)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerarID)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccionPorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCelularVentanaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout VentanaNuevoUsuarioLayout = new javax.swing.GroupLayout(VentanaNuevoUsuario.getContentPane());
        VentanaNuevoUsuario.getContentPane().setLayout(VentanaNuevoUsuarioLayout);
        VentanaNuevoUsuarioLayout.setHorizontalGroup(
            VentanaNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VentanaNuevoUsuarioLayout.setVerticalGroup(
            VentanaNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VentanaTaxis.setTitle("Taxis");
        VentanaTaxis.setMinimumSize(new java.awt.Dimension(1000, 600));
        VentanaTaxis.setModal(true);
        VentanaTaxis.setSize(new java.awt.Dimension(909, 604));

        jListTaxis.setModel(listmodelTaxis);
        jListTaxis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListTaxisValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListTaxis);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos taxi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(909, 604));

        jLabel16.setBackground(new java.awt.Color(0, 0, 255));
        jLabel16.setForeground(java.awt.Color.blue);
        jLabel16.setText("Placa");

        jLabel17.setBackground(new java.awt.Color(0, 0, 255));
        jLabel17.setForeground(java.awt.Color.blue);
        jLabel17.setText("Marca");

        jLabel18.setBackground(new java.awt.Color(0, 0, 255));
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("ID Conductor");

        jLabel19.setBackground(new java.awt.Color(0, 0, 255));
        jLabel19.setForeground(java.awt.Color.blue);
        jLabel19.setText("Modelo");

        jLabel20.setBackground(new java.awt.Color(0, 0, 255));
        jLabel20.setForeground(java.awt.Color.blue);
        jLabel20.setText("Poliza");

        jLabel21.setBackground(new java.awt.Color(0, 0, 255));
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Seguro");

        jLabel22.setBackground(new java.awt.Color(0, 0, 255));
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Fecha Tecno");

        btnEscoger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEscoger.setForeground(new java.awt.Color(0, 0, 255));
        btnEscoger.setText("Seleccionar taxi");
        btnEscoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscogerActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/taxi.png"))); // NOI18N
        jButton2.setFocusPainted(false);

        btnTaxiConMasServicios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTaxiConMasServicios.setForeground(new java.awt.Color(0, 0, 255));
        btnTaxiConMasServicios.setText("Taxi con mas Servicios");
        btnTaxiConMasServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaxiConMasServiciosActionPerformed(evt);
            }
        });

        btnMostrarTodosTaxis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMostrarTodosTaxis.setForeground(java.awt.Color.blue);
        btnMostrarTodosTaxis.setText("Mostrar todos los taxis");
        btnMostrarTodosTaxis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodosTaxisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEscoger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTaxiConMasServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaTecno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarTodosTaxis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(45, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel18))
                            .addComponent(lblIdConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel20))
                    .addComponent(lblPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(lblSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaTecno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEscoger)
                            .addComponent(btnMostrarTodosTaxis))
                        .addGap(18, 18, 18)
                        .addComponent(btnTaxiConMasServicios)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout VentanaTaxisLayout = new javax.swing.GroupLayout(VentanaTaxis.getContentPane());
        VentanaTaxis.getContentPane().setLayout(VentanaTaxisLayout);
        VentanaTaxisLayout.setHorizontalGroup(
            VentanaTaxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaTaxisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        VentanaTaxisLayout.setVerticalGroup(
            VentanaTaxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaTaxisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaTaxisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );

        VentanaMostarUsuarios.setTitle("Mostrar Usuarios");
        VentanaMostarUsuarios.setBounds(new java.awt.Rectangle(0, 0, 773, 512));
        VentanaMostarUsuarios.setMinimumSize(new java.awt.Dimension(726, 598));
        VentanaMostarUsuarios.setSize(new java.awt.Dimension(688, 495));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Usuario");

        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("ID Usuario");

        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Direccion");

        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Tel Fijo");

        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Celular");

        lblUsuario.setBackground(new java.awt.Color(204, 204, 204));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setForeground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Mostusuario.png"))); // NOI18N
        jButton3.setEnabled(false);

        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("Correo electronico");

        btnSeleccionarUsuario.setForeground(new java.awt.Color(0, 0, 255));
        btnSeleccionarUsuario.setText("Seleccionar usuario");
        btnSeleccionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarUsuarioActionPerformed(evt);
            }
        });

        btnUsuariosFrecuentes.setForeground(new java.awt.Color(0, 0, 255));
        btnUsuariosFrecuentes.setText("Usuarios frecuentes");
        btnUsuariosFrecuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosFrecuentesActionPerformed(evt);
            }
        });

        btnViualizarViajes.setForeground(new java.awt.Color(0, 0, 255));
        btnViualizarViajes.setText("Visualizar viajes");
        btnViualizarViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViualizarViajesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltelfijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(lblTelFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSeleccionarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUsuariosFrecuentes, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                    .addComponent(btnViualizarViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(85, 85, 85))
                            .addComponent(lblIDUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(lblDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lbltelfijo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(lblCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel32)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnSeleccionarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsuariosFrecuentes)
                        .addGap(18, 18, 18)
                        .addComponent(btnViualizarViajes)
                        .addGap(20, 20, 20)
                        .addComponent(lblTelFijo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))))
        );

        jListUsuarios.setModel(listmodelUsuarios);
        jListUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListUsuarios);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout VentanaMostarUsuariosLayout = new javax.swing.GroupLayout(VentanaMostarUsuarios.getContentPane());
        VentanaMostarUsuarios.getContentPane().setLayout(VentanaMostarUsuariosLayout);
        VentanaMostarUsuariosLayout.setHorizontalGroup(
            VentanaMostarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMostarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VentanaMostarUsuariosLayout.setVerticalGroup(
            VentanaMostarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaMostarUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        VentanaMostrarServicios.setMinimumSize(new java.awt.Dimension(541, 504));

        jListServicios.setModel(listmodelServicios);
        jListServicios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListServiciosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListServicios);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("ID Servicio");

        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("ID Usuario");

        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("Direccion Origen");

        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("Fecha Servicio");

        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("Hora Servicio");

        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("Placa Taxi");

        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("Valor Servicio");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblPlacaTaxiVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblHoraServicioVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblFechaServicioVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblIDUsuarioVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIDServicioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblValorServicioVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDireccionOrigenVentanaMostrarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblIDServicioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblIDUsuarioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionOrigenVentanaMostrarServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblFechaServicioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblHoraServicioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblPlacaTaxiVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblValorServicioVentanaMostrarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        javax.swing.GroupLayout VentanaMostrarServiciosLayout = new javax.swing.GroupLayout(VentanaMostrarServicios.getContentPane());
        VentanaMostrarServicios.getContentPane().setLayout(VentanaMostrarServiciosLayout);
        VentanaMostrarServiciosLayout.setHorizontalGroup(
            VentanaMostrarServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMostrarServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        VentanaMostrarServiciosLayout.setVerticalGroup(
            VentanaMostrarServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaMostrarServiciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servicio Taxis");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Celular");

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Direccion de Origen");

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Placa Taxi");

        txtCelularVentanaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularVentanaServicioActionPerformed(evt);
            }
        });

        txtPlacataxi.setEditable(false);
        txtPlacataxi.setForeground(new java.awt.Color(0, 0, 255));
        txtPlacataxi.setDisabledTextColor(new java.awt.Color(0, 0, 255));

        jLabel4.setBackground(new java.awt.Color(0, 0, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("NUEVO SERVICIO");

        btnBuscarUsuario.setForeground(java.awt.Color.blue);
        btnBuscarUsuario.setText("Buscar Usuario");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        btnBuscarTaxi.setForeground(java.awt.Color.blue);
        btnBuscarTaxi.setText("Buscar Taxi");
        btnBuscarTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTaxiActionPerformed(evt);
            }
        });

        btnCrearServicio.setForeground(java.awt.Color.blue);
        btnCrearServicio.setText("Crear Servicio");
        btnCrearServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearServicioActionPerformed(evt);
            }
        });

        btnMostrarUsuarios.setForeground(java.awt.Color.blue);
        btnMostrarUsuarios.setText("Mostrar Usuarios");
        btnMostrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarUsuariosActionPerformed(evt);
            }
        });

        btnMostrarServicios.setForeground(java.awt.Color.blue);
        btnMostrarServicios.setText("Mostrar Servicios");
        btnMostrarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarServiciosActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/servicios.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setEnabled(false);

        jLabel33.setBackground(new java.awt.Color(0, 0, 255));
        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("Valor del Servicio");

        btnAgregarUsuarios.setForeground(new java.awt.Color(0, 0, 255));
        btnAgregarUsuarios.setText("Agregar Usuario");
        btnAgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnMostrarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccionOrigen)
                            .addComponent(txtCelularVentanaServicio)
                            .addComponent(txtPlacataxi)
                            .addComponent(txtValorServicio)
                            .addComponent(btnCrearServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnAgregarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCelularVentanaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarUsuarios)
                    .addComponent(btnAgregarUsuarios))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacataxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarTaxi))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cargar Datos");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnCrearServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearServicioActionPerformed

        Random rnd = new Random();
        int IDServicio;
        int aleatorio = rnd.nextInt(1092364363) + 1;

        boolean encontrado = false;
        for (int i = 0; i < listUsuarios.size(); i++) {

            if (aleatorio == (listUsuarios.get(i).getIDUsuario())) {

                encontrado = true;

            }
        }
        if (encontrado) {//Si hay coincidencia o ID EXISTE entonces no agregamos ese ID
//            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "ID encontrado, ya existe");
        } else {//Si no hay coincidencia entonces podemos agregar y usar ese ID
            IDServicio = aleatorio;

//            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "ID no existe");
        }
        try {
            IDServicio = aleatorio;
            int IDUser = Integer.parseInt(txtCelularVentanaServicio.getText());
            String dir = txtDireccionOrigen.getText();
            String placa = txtPlacataxi.getText();
            if (placa.equals("")) {
                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "No hay placa");
            } else {

                LocalDate fecha = LocalDate.now();
                String f = String.valueOf(fecha);
                LocalTime hora = LocalTime.now();
                String h = String.valueOf(hora);
                int valorServicio = Integer.parseInt(txtValorServicio.getText());
                Servicio ser = new Servicio(IDServicio, IDUser, dir, f, h, placa, valorServicio);
                listServicios.add(ser);
                listmodelServicios.removeAllElements();
                listmodelServicios.removeAllElements();
                for (Servicio s : listServicios) {
                    listmodelServicios.addElement(s);
                }
                manDatos.guardarServicios(listServicios, servicios);
                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Servicio creado satisfactoriamente", "CREAR USUARIO", JOptionPane.INFORMATION_MESSAGE);
                txtCelularVentanaServicio.setText("");
                txtDireccionOrigen.setText("");
                txtPlacataxi.setText("");
                txtValorServicio.setText("");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Ingrese datos validos, completos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnCrearServicioActionPerformed

    private void btnBuscarTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTaxiActionPerformed
        txtPlacataxi.setText("");
        VentanaTaxis.setLocationRelativeTo(ProgramaTaxis.this);
        VentanaTaxis.setVisible(true);

    }//GEN-LAST:event_btnBuscarTaxiActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed

        
        try {
            boolean encontrado = false;
            int Posicionencontrada = 0;

            for (int i = 0; i < listUsuarios.size(); i++) {
                int vr = Integer.parseInt(txtCelularVentanaUsuario.getText());
                if (vr == listUsuarios.get(i).getCelular()) {
                    encontrado = true;
                    Posicionencontrada = i;
                }
            }

            if (encontrado) {
                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Usuario ya existe, celular repetido", "ERROR", JOptionPane.WARNING_MESSAGE);

            } else if (txtDireccionPorDefecto.getText().equals("")) {

                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Ingrese direccon por defecto", "ERROR", JOptionPane.WARNING_MESSAGE);
            } else {
                try {
                    String Nombre = txtNombre.getText();
                    int IdUser = Integer.parseInt(txtIDUsuario.getText());
                    String DirDefecto = txtDireccionPorDefecto.getText();
                    String TelFijo = txtTelefonoFijo.getText();
                    int Celular = Integer.parseInt(txtCelularVentanaUsuario.getText());
                    String correo = txtCorreoElectronico.getText();
                    // comprueba que no empieze por punto o @
                    boolean empiezaPuntoArroba = false;
                    Pattern p = Pattern.compile(".^|@^");

                    Matcher m = p.matcher(correo);
                    if (m.find()) {
                        JOptionPane.showMessageDialog(VentanaMostarUsuarios, "Las direcciones email no empiezan por punto o @", "Error", JOptionPane.ERROR_MESSAGE);

                        empiezaPuntoArroba = true;
                    }
                    // comprueba que no empieze por www.
                    p = Pattern.compile("^www.");
                    m = p.matcher(correo);
                    boolean empiezaWWW = false;
                    if (m.find()) {
                        JOptionPane.showMessageDialog(VentanaMostarUsuarios, "Los emails no empiezan por www", "Error", JOptionPane.ERROR_MESSAGE);
                        empiezaWWW = true;

                    }

                    // comprueba que contenga @
                    p = Pattern.compile("@");
                    m = p.matcher(correo);
                    boolean noTieneArroba = false;
                    if (!m.find()) {
                        JOptionPane.showMessageDialog(VentanaMostarUsuarios, "El correo no tiene arroba (@)", "Error", JOptionPane.ERROR_MESSAGE);

                        noTieneArroba = true;
                    }

                    // comprueba que no contenga caracteres prohibidos	
                    p = Pattern.compile("[^A-Za-z0-9.@_-~#]+");
                    m = p.matcher(correo);
                    StringBuffer sb = new StringBuffer();
                    boolean resultado = m.find();

                    boolean caracteresIlegales = false;
                    while (resultado) {
                        caracteresIlegales = true;
                        m.appendReplacement(sb, "");
                        resultado = m.find();
                    }

                    // Añade el ultimo segmento de la entrada a la cadena
                    m.appendTail(sb);

                    correo = sb.toString();

                    if (caracteresIlegales) {
                        JOptionPane.showMessageDialog(VentanaMostarUsuarios, "El correo contiene caracteres ilegales", "Error", JOptionPane.ERROR_MESSAGE);

                    }

                    String pass = "";
                    char[] password = txtContraseña.getPassword();
                    for (int i = 0; i < password.length; i++) {
                        pass += password[i];
                    }
                    if (!pass.equals("") & !(empiezaPuntoArroba) & !(empiezaWWW) & !(noTieneArroba) & !(caracteresIlegales)) {
                        Usuario user = new Usuario(Nombre, IdUser, DirDefecto, TelFijo, Celular, correo, pass);
                        listUsuarios.add(user);
                        listmodelUsuarios.removeAllElements();
                        for (Usuario u : listUsuarios) {
                            listmodelUsuarios.addElement(u);
                        }

                        manDatos.guardarUsuario(listUsuarios, usuarios);
                        JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Usuario creado satisfactriamente", "CREAR USUARIO", JOptionPane.INFORMATION_MESSAGE);
                        VentanaNuevoUsuario.setVisible(false);
//                        txtNombre.setText("");
//                        txtIDUsuario.setText("");
//                        txtDireccionPorDefecto.setText("");
//                        txtTelefonoFijo.setText("");
//                        txtCelularVentanaUsuario.setText("");
//                        txtCorreoElectronico.setText("");
//                        txtContraseña.setText("");
                    }

                } catch (NumberFormatException n) {
                    JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Ingrese datos validos, completos", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Ingrese datos validos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnGenerarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarIDActionPerformed

        txtIDUsuario.setText("");
        Random rnd = new Random();
        int aleatorio = rnd.nextInt(1092364363) + 1;
//        JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Primer random"+"   " +aleatorio);

        boolean encontrado = false;
        for (int i = 0; i < listUsuarios.size(); i++) {

            if (aleatorio == (listUsuarios.get(i).getIDUsuario())) {

                encontrado = true;

            }
        }
        if (encontrado) {//Si hay coincidencia o ID EXISTE entonces no agregamos ese ID
//            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "ID encontrado, ya existe");
        } else {//Si no hay coincidencia entonces podemos agregar y usar ese ID
            String IDUsuario = Integer.toString(aleatorio);
            txtIDUsuario.setText(IDUsuario);
//            JOptionPane.showMessageDialog(VentanaNuevoUsuario, "ID no existe");

        }

    }//GEN-LAST:event_btnGenerarIDActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed

        try {
            boolean encontrado = false;
            int Posicionencontrada = 0;
            boolean vacia = false;
            for (int i = 0; i < listUsuarios.size(); i++) {

                int vr = Integer.parseInt(txtCelularVentanaServicio.getText());

                if (vr == listUsuarios.get(i).getCelular()) {
                    encontrado = true;
                    Posicionencontrada = i;

                }
            }

            if (encontrado) {
                JOptionPane.showMessageDialog(this, "Usuario encontrado");
                txtDireccionOrigen.setText(listUsuarios.get(Posicionencontrada).getDireccion());
            } else {
                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "Usuario no existe");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese celular valido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void VentanaNuevoUsuarioWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_VentanaNuevoUsuarioWindowOpened

    }//GEN-LAST:event_VentanaNuevoUsuarioWindowOpened

    private void btnMostrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsuariosActionPerformed

        VentanaMostarUsuarios.setLocationRelativeTo(null);
        VentanaMostarUsuarios.setVisible(true);

    }//GEN-LAST:event_btnMostrarUsuariosActionPerformed

    private void jListUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUsuariosValueChanged
        int index = jListUsuarios.getSelectedIndex();
        Usuario p = (Usuario) listmodelUsuarios.get(index);

        lblUsuario.setText(p.getNombre());
        lblIDUsuario.setText(String.valueOf(p.getIDUsuario()));
        lblDireccion.setText(p.getDireccion());
        lbltelfijo.setText(p.getTelFijo());
        lblCelular.setText(String.valueOf(p.getCelular()));
        lblCorreo.setText(p.getCorreoElectronico());
    }//GEN-LAST:event_jListUsuariosValueChanged

    private void jListTaxisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListTaxisValueChanged

        try {
            int index = jListTaxis.getSelectedIndex();
            Taxi p = (Taxi) listmodelTaxis.get(index);

            lblPlaca.setText(p.getPlaca());
            lblMarca.setText(p.getMarca());
            lblIdConductor.setText(p.getIDConductor());
            lblModelo.setText(p.getModelo());
            lblPoliza.setText(p.getIDPoliza());
            lblSeguro.setText(p.getIDseguro());
            lblFechaTecno.setText(p.getFechaVencimientoTecnomecanica());
        } catch (ArrayIndexOutOfBoundsException e) {

        }


    }//GEN-LAST:event_jListTaxisValueChanged

    private void txtCelularVentanaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularVentanaServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularVentanaServicioActionPerformed

    private void btnEscogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscogerActionPerformed

        try {
            int index = jListTaxis.getSelectedIndex();
            Taxi p = (Taxi) listmodelTaxis.get(index);
            txtPlacataxi.setText(p.getPlaca());
            VentanaTaxis.setVisible(false);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(VentanaTaxis, "Debe seleccionar un taxi para crear un nuevo Servicio", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEscogerActionPerformed

    private void btnMostrarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarServiciosActionPerformed
        VentanaMostrarServicios.setLocationRelativeTo(null);
        VentanaMostrarServicios.setVisible(true);
    }//GEN-LAST:event_btnMostrarServiciosActionPerformed

    private void jListServiciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListServiciosValueChanged

        int index = jListServicios.getSelectedIndex();
        Servicio p = (Servicio) listmodelServicios.get(index);

        lblIDServicioVentanaMostrarServicio.setText(String.valueOf(p.getIDServicio()));
        lblIDUsuarioVentanaMostrarServicio.setText(String.valueOf(p.getIDUser()));
        lblDireccionOrigenVentanaMostrarServicio.setText(p.getDirOrigen());
        lblFechaServicioVentanaMostrarServicio.setText(p.getFechaServicio());
        lblHoraServicioVentanaMostrarServicio.setText(p.getHoraServicio());
        lblPlacaTaxiVentanaMostrarServicio.setText(p.getPlaca());
        lblValorServicioVentanaMostrarServicio.setText(String.valueOf(p.getValorServicio()));
    }//GEN-LAST:event_jListServiciosValueChanged

    private void btnTaxiConMasServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaxiConMasServiciosActionPerformed

        try {
            String n = JOptionPane.showInputDialog(VentanaTaxis, "Ingrese el numero de servicios que quiere buscar");
            int noServicios = Integer.parseInt(n);
            int vecContadorTaxis[] = new int[listTaxis.size()];

            int contadortaxis = 0;

            for (int i = 0; i < listTaxis.size(); i++) {
                String t = listTaxis.get(i).getPlaca();
                contadortaxis = 0;
                for (int j = 0; j < listServicios.size(); j++) {
                    String s = listServicios.get(j).getPlaca();
                    if (t.equals(s)) {
                        contadortaxis++;
                        vecContadorTaxis[i] = contadortaxis;
                    }
                }
            }

            boolean coincidencia = false;
            ArrayList<Taxi> taxisEncontrados = new ArrayList();
            DefaultListModel listModeltaxisEncontrados = new DefaultListModel();
            for (int i = 0; i < vecContadorTaxis.length; i++) {

                if (vecContadorTaxis[i] >= noServicios) {
                    coincidencia = true;
                    taxisEncontrados.add((Taxi) listmodelTaxis.get(i));

                    //JOptionPane.showMessageDialog(VentanaTaxis, "para la placa:   " + listTaxis.get(i).getPlaca() + "  hay   " + vecContadorTaxis[i] + "   Servicios");
                }
            }
            if (!coincidencia) {
                JOptionPane.showMessageDialog(VentanaTaxis, "No hay placas encontradas que tengan:   " + noServicios + "  Servicios");
            } else {

                
//                listModeltaxisEncontrados.removeAllElements();
//                for (Taxi u : taxisEncontrados) {
//                    listModeltaxisEncontrados.addElement(u);
//                }
//                jListTaxis.setModel(listModeltaxisEncontrados);
                
                listmodelTaxis.removeAllElements();
                for (Taxi u : taxisEncontrados) {
                    listmodelTaxis.addElement(u);
                }
                jListTaxis.setModel(listmodelTaxis);
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(VentanaTaxis, "Ingrese un numero válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnTaxiConMasServiciosActionPerformed

    private void btnAgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuariosActionPerformed

        txtCelularVentanaServicio.setText("");
        VentanaNuevoUsuario.setLocationRelativeTo(ProgramaTaxis.this);
        VentanaNuevoUsuario.setVisible(true);
    }//GEN-LAST:event_btnAgregarUsuariosActionPerformed

    private void btnMostrarTodosTaxisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodosTaxisActionPerformed

        jListTaxis.setModel(listmodelTaxis);
    }//GEN-LAST:event_btnMostrarTodosTaxisActionPerformed

    private void btnSeleccionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarUsuarioActionPerformed
        try {
            int index = jListUsuarios.getSelectedIndex();
            Usuario p = (Usuario) listmodelUsuarios.get(index);
            txtCelularVentanaServicio.setText(String.valueOf(p.getCelular()));
            txtDireccionOrigen.setText(p.getDireccion());
            VentanaMostarUsuarios.setVisible(false);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(VentanaTaxis, "Debe seleccionar un Usuario para crear un nuevo Servicio", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSeleccionarUsuarioActionPerformed

    private void btnUsuariosFrecuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosFrecuentesActionPerformed

        try {
            String n = JOptionPane.showInputDialog(VentanaMostarUsuarios, "Ingrese la frecuencia de viajes para buscar usuarios frecuentes");
            int noServicios = Integer.parseInt(n);
            int vecContadorUsuarios[] = new int[listUsuarios.size()];

            int contadorUsuarios = 0;

            for (int i = 0; i < listUsuarios.size(); i++) {
                int t = listUsuarios.get(i).getIDUsuario();
                contadorUsuarios = 0;
                for (int j = 0; j < listServicios.size(); j++) {
                    int s = listServicios.get(j).getIDUser();
                    if (t == s) {
                        contadorUsuarios++;
                        vecContadorUsuarios[i] = contadorUsuarios;
                    }
                }
            }

            boolean coincidencia = false;
            ArrayList<Usuario> usuariosEncontrados = new ArrayList();
            DefaultListModel listModelUsuariosEncontrados = new DefaultListModel();
            for (int i = 0; i < vecContadorUsuarios.length; i++) {

                if (vecContadorUsuarios[i] >= noServicios) {
                    coincidencia = true;
                    usuariosEncontrados.add((Usuario) listUsuarios.get(i));

                    //JOptionPane.showMessageDialog(VentanaTaxis, "para la placa:   " + listTaxis.get(i).getPlaca() + "  hay   " + vecContadorTaxis[i] + "   Servicios");
                }
            }
            if (!coincidencia) {
                JOptionPane.showMessageDialog(VentanaTaxis, "No hay usuarios que tengan concidencia de:   " + noServicios + "  Servicios");
            } else {

                listModelUsuariosEncontrados.removeAllElements();
                for (Usuario u : usuariosEncontrados) {
                    listModelUsuariosEncontrados.addElement(u);
                }
                jListUsuarios.setModel(listModelUsuariosEncontrados);
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(VentanaTaxis, "Ingrese un numero válido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUsuariosFrecuentesActionPerformed

    private void btnViualizarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViualizarViajesActionPerformed

        VentanaMostrarServicios.setLocationRelativeTo(null);
        
        //VentanaMostrarServicios.setAlwaysOnTop(true);
        VentanaMostrarServicios.setVisible(true);
        try {
            int index = jListUsuarios.getSelectedIndex();
            Usuario p = (Usuario) listmodelUsuarios.get(index);
            int IDUSER = p.getIDUsuario();

            boolean coincidencia = false;
            ArrayList<Servicio> serviciosEncontrados = new ArrayList();
            DefaultListModel listModelserviciosEncontrados = new DefaultListModel();
            for (int i = 0; i < listServicios.size(); i++) {
                if (IDUSER == listServicios.get(i).getIDUser()) {
                    coincidencia = true;
                    serviciosEncontrados.add(listServicios.get(i));
                }
            }
            if (!coincidencia) {
                JOptionPane.showMessageDialog(VentanaNuevoUsuario, "No hay usuarios con estos servicios");
            } else {
                listModelserviciosEncontrados.removeAllElements();
                for (int i = 0; i < serviciosEncontrados.size(); i++) {
                    listModelserviciosEncontrados.addElement(serviciosEncontrados.get(i));
                }
                jListServicios.setModel(listModelserviciosEncontrados);
            }

           
            
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(VentanaTaxis, "Debe seleccionar un usuario para visualizar un nuevo Servicio", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        
    }//GEN-LAST:event_btnViualizarViajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaTaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaTaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaTaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaTaxis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaTaxis().setVisible(true);

            }
        });

    }

    private DefaultListModel listmodelUsuarios;
    private DefaultListModel listmodelServicios;
    private DefaultListModel listmodelTaxis;
    private ManejadorDatos manDatos;
    File usuarios;
    File servicios;
    File taxis;
    ArrayList<Usuario> listUsuarios;
    ArrayList<Servicio> listServicios;
    ArrayList<Taxi> listTaxis;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog VentanaMostarUsuarios;
    private javax.swing.JDialog VentanaMostrarServicios;
    private javax.swing.JDialog VentanaNuevoUsuario;
    private javax.swing.JDialog VentanaTaxis;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAgregarUsuarios;
    private javax.swing.JButton btnBuscarTaxi;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnCrearServicio;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnEscoger;
    private javax.swing.JButton btnGenerarID;
    private javax.swing.JButton btnMostrarServicios;
    private javax.swing.JButton btnMostrarTodosTaxis;
    private javax.swing.JButton btnMostrarUsuarios;
    private javax.swing.JButton btnSeleccionarUsuario;
    private javax.swing.JButton btnTaxiConMasServicios;
    private javax.swing.JButton btnUsuariosFrecuentes;
    private javax.swing.JButton btnViualizarViajes;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListServicios;
    private javax.swing.JList<String> jListTaxis;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionOrigenVentanaMostrarServicio;
    private javax.swing.JLabel lblFechaServicioVentanaMostrarServicio;
    private javax.swing.JLabel lblFechaTecno;
    private javax.swing.JLabel lblHoraServicioVentanaMostrarServicio;
    private javax.swing.JLabel lblIDServicioVentanaMostrarServicio;
    private javax.swing.JLabel lblIDUsuario;
    private javax.swing.JLabel lblIDUsuarioVentanaMostrarServicio;
    private javax.swing.JLabel lblIdConductor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlacaTaxiVentanaMostrarServicio;
    private javax.swing.JLabel lblPoliza;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblTelFijo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblValorServicioVentanaMostrarServicio;
    private javax.swing.JLabel lbltelfijo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JTextField txtCelularVentanaServicio;
    private javax.swing.JTextField txtCelularVentanaUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtDireccionOrigen;
    private javax.swing.JTextField txtDireccionPorDefecto;
    private javax.swing.JTextField txtIDUsuario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlacataxi;
    private javax.swing.JTextField txtTelefonoFijo;
    private javax.swing.JTextField txtValorServicio;
    // End of variables declaration//GEN-END:variables

}
